version = 2
final_space = true
console_title_template = "{{if .Root}}[root] {{end}}{{.Shell}} in <{{.Folder}}>"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "os"
style = "powerline"
# # powerline_symbol = ""
template = "{{ if .WSL }}WSL at{{ end }} {{.Icon}} "
background = "p:bg"
foreground = "p:fg"

[[blocks.segments]]
type = "path"
style = "powerline"
# powerline_symbol = ""
template = " {{ .Path }} "
background = "p:blue_s"
foreground = "p:bg0_h"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
type = "git"
style = "powerline"
# powerline_symbol = ""
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow_s{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:orange_s{ end }}",
  "{{ if gt .Ahead 0 }}p:purple_s{{ end }}",
  "{{ if gt .Behind 0 }}p:purple_s{{ end }}",
]
template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
background = "p:green_s"
foreground = "p:bg0_h"

[blocks.segments.properties]
branch_icon = " "
branch_identical_icon = "●"
commit_icon = "@"
branch_max_length = 25.0
fetch_stash_count = true
fetch_status = true
display_status_detail = false

[[blocks.segments]]
type = "go"
style = "powerline"
# powerline_symbol = ""
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
background = "p:fg"
foreground = "p:bg0_h"


[blocks.segments.properties]
fetch_version = true

[[blocks.segments]]
type = "julia"
style = "powerline"
# powerline_symbol = ""
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
background = "p:fg"
foreground = "p:bg0_h"


[blocks.segments.properties]
fetch_version = true

[[blocks.segments]]
type = "python"
style = "powerline"
# powerline_symbol = ""
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}({{ .Venv }}) {{ end }}{{ .Full }}{{ end }} "
background = "p:fg"
foreground = "p:bg0_h"

[blocks.segments.properties]
display_mode = "context"
home_enabled = true
# fetch_virtual_env = true
# folder_name_fallback = false

[[blocks.segments]]
type = "ruby"
style = "powerline"
# powerline_symbol = ""
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
background = "p:fg"
foreground = "p:bg0_h"


[blocks.segments.properties]
display_mode = "files"
fetch_version = true

[[blocks.segments]]
type = "azfunc"
style = "powerline"
# powerline_symbol = ""
template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
background = "p:fg"
foreground = "p:bg0_h"


[blocks.segments.properties]
display_mode = "files"
fetch_version = false

[[blocks.segments]]
type = "aws"
style = "powerline"
# powerline_symbol = ""
background_templates = [
  "{{if contains 'default' .Profile}}p:fg{{end}}",
  "{{if contains 'jan' .Profile}}p:fg{{end}}",
]
template = "  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
foreground = "p:bg0_h"


[blocks.segments.properties]
display_default = false

[[blocks.segments]]
type = "root"
style = "powerline"
# powerline_symbol = ""
template = "  "
background = "p:fg"
foreground = "p:bg0_h"


[[blocks]]
type = "rprompt"
overflow = "hidden"

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "p:aqua_s"
background = "transparent"
template = "{{ .FormattedMs }}"

[blocks.segments.properties]
threshold = 5000

# [[blocks]]
#   type = "prompt"
#   alignment = "right"

#   [[blocks.segments]]
#     type = "executiontime"
#     style = "plain"
#     template = "{{.FormattedMs}}"
#     background = "transparent"
#     foreground = "#8ec07c"

#     [blocks.segments.properties]
#       style = "austin"
#       threshold = 0.0

#   [[blocks.segments]]
#     type = "time"
#     style = "plain"
#     template = " · </>{{.CurrentDate | date .Format}}"
#     background = "transparent"
#     foreground = "#8ec07c"

#     [blocks.segments.properties]
#       # time_format = "02/01/06 15:04"
#       time_format = "15:04"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "status"
style = "plain"
foreground_templates = ["{{if gt .Code 0}}p:red_s{{end}}"]
template = "❯"
background = "transparent"
foreground = "p:aqua_s"

[blocks.segments.properties]
always_enabled = true


[transient_prompt]
type = "status"
style = "plain"
foreground_templates = ["{{if gt .Code 0}}p:red_s{{end}}"]
template = "❯ "
background = "transparent"
foreground = "p:aqua_s"


[secondary_prompt]
foreground = "p:aqua_s"
background = "transparent"
template = "❯❯ "

[palette]
bg = "#282828"
bg0_h = "#1D2021"
fg = "#EBDBB2"
red = "#CC241D"
red_s = "#FB4934"
green = "#B8BB26"
green_s = "#B8BB26"
yellow = "#D79921"
yellow_s = "#FABD2F"
blue = "#458588"
blue_s = "#83A598"
purple = "#B16286"
purple_s = "#D3869B"
aqua = "#689D6A"
aqua_s = "#8EC07C"
gray = "#A89984"
gray_s = "#928374"
orange = "#D65D0E"
orange_s = "#FE8019"
