console_title_template = '{{if .Root}}[root] {{end}}{{.Shell}} in <{{.Folder}}>'
version = 3
final_space = true

[palette]
  aqua = '#689D6A'
  aqua_s = '#8EC07C'
  bg = '#282828'
  bg0_h = '#1D2021'
  blue = '#458588'
  blue_s = '#83A598'
  fg = '#EBDBB2'
  gray = '#A89984'
  gray_s = '#928374'
  green = '#B8BB26'
  green_s = '#B8BB26'
  orange = '#D65D0E'
  orange_s = '#FE8019'
  purple = '#B16286'
  purple_s = '#D3869B'
  red = '#CC241D'
  red_s = '#FB4934'
  yellow = '#D79921'
  yellow_s = '#FABD2F'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:aqua_s'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = 'p:aqua_s'
  background = 'transparent'
  type = 'status'
  style = 'plain'
  foreground_templates = ['{{if gt .Code 0}}p:red_s{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ if .WSL }}WSL at{{ end }} {{.Icon}} '
    foreground = 'p:fg'
    background = 'p:bg'
    type = 'os'
    style = 'powerline'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = 'p:bg0_h'
    background = 'p:blue_s'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = 'p:bg0_h'
    background = 'p:green_s'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow_s{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:orange_s{ end }}', '{{ if gt .Ahead 0 }}p:purple_s{{ end }}', '{{ if gt .Behind 0 }}p:purple_s{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      branch_identical_icon = '●'
      branch_max_length = 25.0
      commit_icon = '@'
      display_status_detail = false
      fetch_stash_count = true
      fetch_status = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:bg0_h'
    background = 'p:fg'
    type = 'go'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:bg0_h'
    background = 'p:fg'
    type = 'julia'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}({{ .Venv }}) {{ end }}{{ .Full }}{{ end }} '
    foreground = 'p:bg0_h'
    background = 'p:fg'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'context'
      home_enabled = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:bg0_h'
    background = 'p:fg'
    type = 'ruby'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = 'p:bg0_h'
    background = 'p:fg'
    type = 'azfunc'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
    foreground = 'p:bg0_h'
    type = 'aws'
    style = 'powerline'
    background_templates = ["{{if contains 'default' .Profile}}p:fg{{end}}", "{{if contains 'jan' .Profile}}p:fg{{end}}"]

    [blocks.segments.properties]
      display_default = false

  [[blocks.segments]]
    template = '  '
    foreground = 'p:bg0_h'
    background = 'p:fg'
    type = 'root'
    style = 'powerline'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:aqua_s'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    foreground = 'p:aqua_s'
    background = 'transparent'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red_s{{end}}']

    [blocks.segments.properties]
      always_enabled = true
